name: Build Padavan Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        model: [Mi-R3P]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gawk git subversion libncurses5-dev zlib1g-dev \
              gperf gettext unzip python3 python3-pip curl libssl-dev bc

      - name: Setup Go 1.23.0
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.0
          cache: 'go'

      - name: Verify Go version
        run: go version

      - name: Cache toolchain
        uses: actions/cache@v3
        with:
          path: padavan/toolchain
          key: ${{ runner.os }}-padavan-toolchain-${{ hashFiles('padavan/toolchain/**') }}
          restore-keys: |
            ${{ runner.os }}-padavan-toolchain-

      - name: Download and extract toolchain
        if: steps.cache-toolchain.outputs.cache-hit != 'true'
        run: |
          curl -L -o toolchain.tar.gz https://github.com/your-username/your-repo/releases/download/v1.0/toolchain.tar.gz
          mkdir -p padavan/toolchain
          tar -xzf toolchain.tar.gz -C padavan/toolchain

      - name: Setup toolchain
        run: |
          export PATH=$(pwd)/padavan/toolchain/bin:$PATH
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Clean sources
        working-directory: padavan/source
        run: |
          ../../tools/clean_sources.sh

      - name: Setup sources
        working-directory: padavan/source
        run: |
          ../../tools/setup_toolchain.sh

      - name: Configure build for ${{ matrix.model }}
        working-directory: padavan/source
        run: |
          source ../../build.config
          cp configs/templates/${{ matrix.model }}.config configs/my_build.config

      - name: Build Firmware for ${{ matrix.model }}
        working-directory: padavan/source
        run: |
          ./build_firmware_modify ${{ matrix.model }}

      - name: Upload Firmware for ${{ matrix.model }}
        uses: actions/upload-artifact@v3
        with:
          name: padavan-firmware-${{ matrix.model }}-${{ github.sha }}
          path: padavan/source/images/*.trx
