name: Build Padavan Firmware

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: 'no'
  release:
    types: [published]

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-20.04
    if: ${{ !(github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) }}
    env:
      images_dir: /opt/images
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install -y build-essential gawk git subversion libncurses5-dev zlib1g-dev \
              gperf gettext unzip python3 python3-pip curl libssl-dev bc

      - name: Install Go
        run: |
          wget https://golang.org/dl/go1.23.0.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.23.0.linux-amd64.tar.gz
          echo 'export PATH=$PATH:/usr/local/go/bin' >> $GITHUB_ENV

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Prepare toolchain
        run: |
          cd toolchain-mipsel
          sh dl_toolchain.sh

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'yes' }}
        with:
          limit-access-to-actor: true

      - name: Start build
        run: |
          cd Padavan/trunk  # 确保目录正确
          mkdir -p ${images_dir}
          # 指定要编译的机型为 R3P
          target="R3P"  # 将机型设置为 R3P
          fakeroot ./build_firmware_ci $target
          if [ $? = 0 ]; then
            cp -f images/*.trx ${images_dir}/$target.trx
          else
            exit 1
          fi
          ./clear_tree_simple >/dev/null 2>&1

      - name: Create archive
        if: ${{ github.event_name != 'release' && success() }}
        run: |
          ls -lh ${images_dir}
          GIT_VERSION=$(git rev-parse --short=7 HEAD 2>/dev/null) && [ -n "$GIT_VERSION" ] && \
          image_name=images_${GIT_VERSION} || image_name=images
          cd ${images_dir}
          md5sum *.trx | tee md5sum.txt
          7z a -mx=9 ${image_name}.7z ./*
          echo "image_name=${image_name}" >> $GITHUB_ENV

      - name: Upload images to Artifact
        if: ${{ github.event_name != 'release' && success() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.image_name }}
          path: ${{ env.images_dir }}/*.7z

      - name: Upload images to Releases
        if: ${{ github.event_name == 'release' && success() }}
        uses: svenstaro/upload-release-action@2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.images_dir }}/*.trx
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
